# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a637905de6f56e64d8da013bc11d7f6e4dd49916e7a2d830aa5dabba577e3b9dff37ef1bfa15c69895316a68c90469e2309168738d9cb2e39f33a8e2052f753

test:
  secret_key_base: 7cd2bfcf436ff02b06f16946210dbdb69be4e75a1a750618e6a397b77bf863045632e82485a423b6e999134a40551024bdcb37524accfee2b1b8ba6225e42393

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
